version: '3.8'
services:
  back-end:
    build: ./back-end
    ports:
      - "8000:8000"
    volumes:
      - ./back-end:/var/www/html
    depends_on:
      - redis

  front-end-web:
    build: ./front-end-web
    ports:
      - "5173:5173"
    volumes:
      - ./front-end-web:/app

  # frontend-mobile:
  #   build: ./front-end
  #   ports:
  #     - "###:###"
  #   volumes:
  #     - ./front-end-mobile:/app

  # fastapi:
  #   build: ./fastapi-ms
  #   ports:
  #     - "8001:8001"
  #   volumes:
  #     - ./fastapi-ms:/app

  # redis:
  #   image: redis:alpine
